: '
Tmux is a terminal multiplexer; it allows you to create several "pseudo terminals" from a single terminal. 
This is very useful for running multiple programs with a single connection, such as when you're remotely connecting to a machine 
using Secure Shell (SSH).

Tmux also decouples your programs from the main terminal, protecting them from accidentally disconnecting. You can detach tmux 
from the current terminal, and all your programs will continue to run safely in the background. Later, you can reattach tmux to 
the same or a different terminal.

In addition to its benefits with remote connections, tmux's speed and flexibility make it a fantastic tool to manage multiple 
terminals on your local machine, similar to a window manager. I've been using tmux on my laptops for over eight years. Some of 
tmux's features that help me and increase my productivity include:
'

# Open a new session in tmux without any name. An ID number is autogenerated for later session reconnect.
tmux

# OR
tmux new

#OR
tmux new-session


# Create a named session
tmux new-session -s <new-session-name>

# Example: 
tmux new-session -s minecraft-server

# To Detach from a named session press => Ctrl + B Then D
# To scroll inside a tmux session press => Ctrl + [, Then use page up/down or arrow keys to scroll. q to quit scroll mode.

# List all active tmux sessions
tmux ls

#OR
tmux list-sessions

# Output Example - 0: 1 windows (created Sat Aug 27 20:54:58 2022)

# Reconnect to existing session in above example

tmux attach -t 0

#OR to attach to most recent session
tmux a

#OR use abbreviation
tmux at 
tmux attach
tmux attach-session


# Rename a session from inside the seesion
# Go to command mode with => Ctrl + B
# Then, $ => rename session
# d=> to detach from current session
# ( OR ) => move between sessions

# kill last active session
tmux kill-session

# Kill session with name
tmux kill-session -t <session-name>

# Kill all session except session0
tmux kill-ses -a -t session0

 


